model_class: Models.BaselinePulse.BaselinePulseModel
resolution: 224
max_length: 512

root_dir: /oriondata/AIMLab/Yohan/Databases
evaluation_strategy: steps
save_strategy: steps
eval_steps: 200
save_steps: 200
load_best_model_at_end: true
metric_for_best_model: ANLS
train_datasets: [PULSE]
val_datasets: [PULSE_VAL]
test_datasets: [PULSE_TEST]
val_dataset_limit: 100
json_filename: data.json
attn_implementation: flash_attention_2
report_to: ["tensorboard"]
bf16: true
fp16: false
ddp_find_unused_parameters: false
torch_dtype: bfloat16
low_cpu_mem_usage: true
device_map: auto

model_pretrained: "PULSE-ECG/PULSE-7B"

generation_config:
  max_new_tokens: 32    # au lieu de 5
  temperature: 0.7       # au lieu de 0.0
  do_sample: True